      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d "fullstack-devops-app" ]; then
              git clone https://github.com/Misbah-Ashiq/fullstack-devops-app.git
            fi
            cd fullstack-devops-app
            git reset --hard
            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans
-orphans

            docker compose up -d
